### ISSUE TITLE
Latest release images missing

### ISSUE THREAD

**Issue by Christoph-Raab** [kubernetes/dns#579]
Wanted to upgrade to 1.22.19 or 1.22.20, but both images can not be pulled. Is the mentioned registry still valid? 1.22.18 still works.

```shell
$ docker pull registry.k8s.io/dns/k8s-dns-node-cache:1.22.20
Error response from daemon: manifest for registry.k8s.io/dns/k8s-dns-node-cache:1.22.20 not found: manifest unknown: Failed to fetch "1.22.20"
$ docker pull registry.k8s.io/dns/k8s-dns-node-cache:1.22.19
Error response from daemon: manifest for registry.k8s.io/dns/k8s-dns-node-cache:1.22.19 not found: manifest unknown: Failed to fetch "1.22.19"
$ docker pull registry.k8s.io/dns/k8s-dns-node-cache:1.22.18
1.22.18: Pulling from dns/k8s-dns-node-cache
791162134625: Pull complete 
3c8d386a09a4: Pull complete 
98e94c574874: Pull complete 
5887c975c645: Pull complete 
fd7341482f8b: Pull complete 
Digest: sha256:6edf05a385e854def4b34cdca0778585303e1d734861b989029541ec1192d2b1
Status: Downloaded newer image for registry.k8s.io/dns/k8s-dns-node-cache:1.22.18
registry.k8s.io/dns/k8s-dns-node-cache:1.22.18

```

**Comment by dpasiukevich** [comment]
Hi, if possible, could you make an image promotion PR for 1.22.19 and 1.22.20? (example https://github.com/kubernetes/k8s.io/pull/4603)

**Comment by Christoph-Raab** [comment]
Tried to, but apparently I'd need a google cloud account to access the information required for that.

```bash
$ python parse-image-sha.py 1.22.19
k8s-dns-dnsmasq-nanny:
    "sha256:8f4b801fcd7a21aecea42e0880109ebb292be3df3ef11d433b82c1470f88df25": ["1.22.19"]
Get "https://gcr.io/v2/k8s-staging-dns/k8s-dns-dnsmasq-nanny/manifests/1.22.19": unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
Traceback (most recent call last):
  File "parse-image-sha.py", line 60, in <module>
    main()
  File "parse-image-sha.py", line 52, in main
    parsed = json.loads(out)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Don't see a quick way to set this up on my workstation, since we don't use google cloud.
