### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by mintzhao** [kubernetes/dns#93]
## version
1.14.1

## fatal output
```
fatal error: concurrent map writes

goroutine 69 [running]:
runtime.throw(0x162294a, 0x15)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4206335c8 sp=0xc4206335a8
runtime.mapassign1(0x1465c20, 0xc4202ada10, 0xc420633820, 0xc4206337d8)
	/usr/local/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc4206336b0 sp=0xc4206335c8
k8s.io/dns/pkg/dns.(*KubeDNS).generateRecordsForHeadlessService(0xc42018c100, 0xc420675798, 0xc420044cb0, 0x0, 0x0)
	/go/src/k8s.io/dns/pkg/dns/dns.go:504 +0x860 fp=0xc420633850 sp=0xc4206336b0
k8s.io/dns/pkg/dns.(*KubeDNS).addDNSUsingEndpoints(0xc42018c100, 0xc420675798, 0xc420122a50, 0xc420122a48)
	/go/src/k8s.io/dns/pkg/dns/dns.go:420 +0xc2 fp=0xc420633890 sp=0xc420633850
k8s.io/dns/pkg/dns.(*KubeDNS).handleEndpointAdd(0xc42018c100, 0x15e9060, 0xc420675798)
	/go/src/k8s.io/dns/pkg/dns/dns.go:319 +0x52 fp=0xc4206338c0 sp=0xc420633890
k8s.io/dns/pkg/dns.(*KubeDNS).handleEndpointUpdate(0xc42018c100, 0x15e9060, 0xc420675798, 0x15e9060, 0xc420675798)
	/go/src/k8s.io/dns/pkg/dns/dns.go:382 +0x4f8 fp=0xc420633b28 sp=0xc4206338c0
k8s.io/dns/pkg/dns.(*KubeDNS).(k8s.io/dns/pkg/dns.handleEndpointUpdate)-fm(0x15e9060, 0xc420675798, 0x15e9060, 0xc420675798)
	/go/src/k8s.io/dns/pkg/dns/dns.go:246 +0x52 fp=0xc420633b60 sp=0xc420633b28
k8s.io/dns/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(0xc4204ad310, 0xc4204ad320, 0xc4204ad330, 0x15e9060, 0xc420675798, 0x15e9060, 0xc420675798)
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/tools/cache/controller.go:180 +0x5d fp=0xc420633b90 sp=0xc420633b60
k8s.io/dns/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnUpdate(0xc4203db280, 0x15e9060, 0xc420675798, 0x15e9060, 0xc420675798)
	<autogenerated>:51 +0x8c fp=0xc420633bd8 sp=0xc420633b90
k8s.io/dns/vendor/k8s.io/client-go/tools/cache.NewInformer.func1(0x148db60, 0xc4201a92a0, 0xc4201a92a0, 0x148db60)
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/tools/cache/controller.go:246 +0x335 fp=0xc420633ca8 sp=0xc420633bd8
k8s.io/dns/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc420132370, 0xc4202adb60, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:420 +0x22a fp=0xc420633d80 sp=0xc420633ca8
k8s.io/dns/vendor/k8s.io/client-go/tools/cache.(*Controller).processLoop(0xc420462150)
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/tools/cache/controller.go:131 +0x3c fp=0xc420633dc0 sp=0xc420633d80
k8s.io/dns/vendor/k8s.io/client-go/tools/cache.(*Controller).(k8s.io/dns/vendor/k8s.io/client-go/tools/cache.processLoop)-fm()
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/tools/cache/controller.go:102 +0x2a fp=0xc420633dd8 sp=0xc420633dc0
k8s.io/dns/vendor/k8s.io/client-go/pkg/util/wait.JitterUntil.func1(0xc420633f70)
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/pkg/util/wait/wait.go:96 +0x5e fp=0xc420633e10 sp=0xc420633dd8
k8s.io/dns/vendor/k8s.io/client-go/pkg/util/wait.JitterUntil(0xc420633f70, 0x3b9aca00, 0x0, 0x13e8501, 0xc4203f02a0)
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/pkg/util/wait/wait.go:97 +0xad fp=0xc420633ed8 sp=0xc420633e10
k8s.io/dns/vendor/k8s.io/client-go/pkg/util/wait.Until(0xc420633f70, 0x3b9aca00, 0xc4203f02a0)
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/pkg/util/wait/wait.go:52 +0x4d fp=0xc420633f10 sp=0xc420633ed8
k8s.io/dns/vendor/k8s.io/client-go/tools/cache.(*Controller).Run(0xc420462150, 0xc4203f02a0)
	/go/src/k8s.io/dns/vendor/k8s.io/client-go/tools/cache/controller.go:102 +0x1af fp=0xc420633f90 sp=0xc420633f10
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420633f98 sp=0xc420633f90
created by k8s.io/dns/pkg/dns.(*KubeDNS).Start
	/go/src/k8s.io/dns/pkg/dns/dns.go:148 +0x9f
```

## cause
```
func (kd *KubeDNS) generateRecordsForHeadlessService(e *v1.Endpoints, svc *v1.Service) error {
	subCache := treecache.NewTreeCache()
	glog.V(4).Infof("Endpoints Annotations: %v", e.Annotations)
	for idx := range e.Subsets {
		for subIdx := range e.Subsets[idx].Addresses {
			address := &e.Subsets[idx].Addresses[subIdx]
			endpointIP := address.IP
			recordValue, endpointName := util.GetSkyMsg(endpointIP, 0)
			if hostLabel, exists := getHostname(address); exists {
				endpointName = hostLabel
			}
			subCache.SetEntry(endpointName, recordValue, kd.fqdn(svc, endpointName))
			for portIdx := range e.Subsets[idx].Ports {
				endpointPort := &e.Subsets[idx].Ports[portIdx]
				if endpointPort.Name != "" && endpointPort.Protocol != "" {
					srvValue := kd.generateSRVRecordValue(svc, int(endpointPort.Port), endpointName)
					glog.V(2).Infof("Added SRV record %+v", srvValue)

					l := []string{"_" + strings.ToLower(string(endpointPort.Protocol)), "_" + endpointPort.Name}
					subCache.SetEntry(endpointName, srvValue, kd.fqdn(svc, append(l, endpointName)...), l...)
				}
			}

			// Generate PTR records only for Named Headless service.
			if _, has := getHostname(address); has {
				reverseRecord, _ := util.GetSkyMsg(kd.fqdn(svc, endpointName), 0)
				kd.reverseRecordMap[endpointIP] = reverseRecord // concurrent map writes
			}
		}
	}
	subCachePath := append(kd.domainPath, serviceSubdomain, svc.Namespace)
	kd.cacheLock.Lock()
	defer kd.cacheLock.Unlock()
	kd.cache.SetSubCache(svc.Name, subCache, subCachePath...)
	return nil
}

```

**Comment by MrHohn** [comment]
Fixed in 1.14.2. Related PR #79.
